### ISSUE TITLE
How to layer with tokio timeout?

### ISSUE THREAD

**Issue by gitmalong** [bwintertkb/retry_macro#2]
I feel I really would like to use something like hyper for async calls because adding retry, timeout functionality on top makes the code look quite ugly. However I still tried with this macro:

```rust
  let timeout_call = tokio::time::timeout(Duration::from_secs(30), my_async_call(cp));
  retry_async!(5, timeout_call).unwrap();
```

makes the compiler throw
```
unexpected end of macro invocation
missing tokens in macro argument
```

Is it because macro arguments are mandatory?

**Comment by bwintertkb** [comment]
Hey mate,

This is a trickier one but I believe it does not work because the function arguments need to implement a clone/copy (not sure if that is the issue) but the function needs to be callable. `timeout` returns a `Timeout` struct that you simply await on. The macro itself needs something callable (i.e. something that require parenthesis to be evaluated).

Please let me know if this answers your querie :) By the way I did notice that the `retry_macro` did not accept none-argument functions without trailing commas, I've changed that in the latest push (version `0.2.0`).
